JuliaStats/MultivariateStats.jl

- src/pca.jl
- test/pca.jl
Call to `fit(PCA, X)` fails if `X` is `Float32` array. This pull request adds a test and fixes it. I'm also fixing `pcacov` and `pcasvd` as they seem to have the same issue.
> Fix an issue with PCA not working with Float32 arrays

- src/pca.jl
Due to floating point inaccuracies, the sum of principal variances can slightly exceed  the total variance.
https://github.com/JuliaStats/MultivariateStats.jl/issues/17
> fixed possible error due to floating point inaccuracies

- REQUIRE
- src/MultivariateStats.jl
- src/cmds.jl
- src/pca.jl
- src/whiten.jl
- test/cca.jl
- test/ica.jl
- test/lda.jl
- test/lreg.jl
- test/pca.jl
- test/whiten.jl
Use `Compat.LinAlg.checksquare`. This should make the package work again on 0.5.
> Update tests to new row slicing and cov behavior. 

- .travis.yml
- REQUIRE
- docs/source/mclda.rst
- src/MultivariateStats.jl
- src/lda.jl
- test/cca.jl
- test/cmds.jl
- test/lda.jl
- test/mclda.jl
- test/pca.jl
The current multicomponent LDA algorithm stores the scatter (covariance) matrices, which in `d` dimensions is a `d-by-d` matrix. When `d` gets big (e.g., of order 10^6), this is bad news. This PR adds an alternative implementation of LDA that does not require storage of the scatter matrices. It also features regularization by projecting down to the subspace spanned by the within-class scatter, and consequently does not require "extra" regularization.
Moreover, this fixes errors due to Base now exporting `view`, and depwarns from `scale` and `issymmetric`. One note of caution: Compat now defines `view` as an alias for `slice`, and on julia-0.3 `slice` was slow compared to `ArrayViews`. So this could cause a pretty serious performance hit for julia-0.3 users. Perhaps we should bump the …
> Add high-dimensional LDA algorithm; fix julia-0.5 depwarns/errors

- docs/source/mclda.rst
- src/lda.jl
- test/mclda.jl
If you're performing LDA on data sets in which the number of points per class varies widely, the definition of the within- and between-class scatter matrices used in this package is dominated by the classes with the most points; a small cluster might have negligible impact on the final choice of directions. In many applications, this is undesirable. There is [a self-consistent alternative definition](http://stats.stackexchange.com/questions/123490/what-is-the-correct-formula-for-between-class-scatter-matrix-in-lda) of LDA which normalizes for the number of points per class. This implements normalization *as an option* for the `SubspaceLDA` formulation.
Note that once we get this through the review process and merge it, someone needs to push an update to the documentation.
> Add a normalization option to SubspaceLDA

- src/lda.jl
- test/mclda.jl
This makes MulticlassLDA work on 32-bit floating-point numbers as well.
> support 32-bit MulticlassLDA

- REQUIRE
- src/ica.jl
- src/ppca.jl
- test/ica.jl
- test/ppca.jl
> Added Convergence Exceptions for PPCA (EM & Bayes methods) & ICA (fastica!)

- src/kpca.jl
- test/kpca.jl
Kernel centering was calculated incorrectly and with error for a non-square matrices. This PR fixes this bug. This will fix #44.
> Fixed kernel centering

- Project.toml
- src/cca.jl
- src/common.jl
- src/pca.jl
- test/cca.jl
Fixed CCA type constraints (closes #53)
In addition:
- Removed `Printf` dependency
- Refactored CCA tests
> Fixed CCA type constraints

- docs/source/cmds.rst
- src/MultivariateStats.jl
- src/cmds.jl
- src/common.jl
- src/kpca.jl
- test/cmds.jl
Changed cMDS to have a standard `fit/transform` API
New:
- include eigenvalues in a result (#60)
Added:
> New MDS API

- src/kpca.jl
- test/kpca.jl
Throw proper error in `transform(M)` if a precomputed kernel is not provided
Fixes #96 .
> KPCA: throw proper error in `transform(M)`

- docs/source/pca.rst
I ran into a problem when trying the PCA example.  Looks like DataArrays.jl is deprecated and the current version of DataFrame allows easy conversion to Matrix or Vector.
My config:
```
(v1.1) pkg> st DataFrames
Status `~/.julia/environments/v1.1/Project.toml`
[a93c6f00] DataFrames v0.18.2
[2913bbd2] StatsBase v0.30.0
[bd369af6] Tables v0.2.4
(v1.1) pkg> st MultivariateStats
Status `~/.julia/environments/v1.1/Project.toml`
[6f286f6a] MultivariateStats v0.6.0
[2913bbd2] StatsBase v0.30.0
```
> stop using DataArray for conversion

- docs/source/lreg.rst
- src/lreg.jl
- test/lreg.jl
Deprecate `trans` in favor of `dims`  argument
> LREG: deprecate `trans` argument

- src/common.jl
- src/lda.jl
This PR loosen type restriction in `MulticlassLDA` and `MulticlassldaStats`. This was done to allow using `CovarianceEstimator`'s from **CovarianceEstimation.jl** and other more general Estimators in estimating scattter matrices used in `MuticlassLDA` model. (which is currently not possible on #master).
I believe this would help other packages integrate better with MultivariateStats
@wildart
> loosen type bounds in `MulticlassLDA` and `MulticlassldaStats`

- .github/workflows/CompatHelper.yml
- .travis.yml
- Project.toml
- src/cmds.jl
- test/cmds.jl
`fit(MDS, ...)` lacked documentation, and consequently I simply assumed
that one  passed a matrix of distances. This did not trigger any errors, but the
results were nonsense, because the distances matrix was interpreted as
a data matrix.
We can address this by requiring the user to provide the `distances` keyword.
Note that this is a **breaking change** and so I've taken liberty to bump the minor version.
> Require `distances` keyword for MDS

- test/ica.jl
- test/ppca.jl
Hopefully this will get the package passing tests. This may not be a real fix, but my guess is that what happened is that with changes in the Julia version, the random numbers change their values. Generally I find it better to construct deterministic tests, but I don't have the time to figure out all the stuff I'd need to do for that; perhaps those that use the ICA & PPCA functionality can do so at a later time.
> Bandaids for busted tests

- docs/source/mclda.rst
- docs/source/whiten.rst
Replaced the pre-0.6 type/immutable keywords in the .rst documentation with (mutable)
struct, so it now matches the code.
> Modernize struct names in docs

- src/MultivariateStats.jl
This export was added by 856bb6a even before the feature was introduced, and later 1010d72 added only `_invsqrtm!`. So this has never worked.
> Remove nonexistent export of invsqrtm

- .github/workflows/ci.yml
- Project.toml
- src/MultivariateStats.jl
- src/cmds.jl
- src/common.jl
- src/kpca.jl
- test/cmds.jl
- test/kpca.jl
Removed `pairwise` forced symmetry for non-symmetric kernels.  Fixes #143.
> fixed `pairwise` for non-symmetric kernels

- docs/make.jl
- docs/src/index.md
- docs/src/lreg.md
- src/MultivariateStats.jl
- src/lreg.jl
- test/lreg.jl
In addition, I added an isotonic regression implementation.
> Refactor regression code and docs (for #109)

- README.md
- docs/src/mds.md
- src/MultivariateStats.jl
- src/cmds.jl
- src/common.jl
- src/lreg.jl
- src/mmds.jl
- test/cmds.jl
Implementation of weighted (non)metric MDS with transformed proximities.
> Metric MDS

- src/common.jl
- src/lda.jl
- src/mmds.jl
- test/mclda.jl
Previously, in MC-LDA & SubLDA, labels required to be from a set of integers in the range `1:nc` where `nc` is a total number of classes. That created a problem when some labels in this range where not present in the label collection. e.g. `[1,1,3,3,3]` label collection has two classes but maximum value of label is `3`. This was intentional design decision because label set was used for indexing features during calculation of feature centers. Thus, to avoid incorrect indexing the number of classes parameter was used.
This PR removes the "number of classes" parameter and estimates a number of classes from a number of unique labels. Additionally, PR removes type limitation on label collection.
> Remove number of classes parameter from *-LDA

- src/lda.jl
- test/mclda.jl
This PR resolves #200. 
It also includes a new exception called `NullMatrixException` which is thrown when a null matrix is detected at run-time. 
Additionally, Efforts have been made to detect the case when the between-class covariance matrix is null (i.e the zero matrix) based on the input to the `fit(SubspaceLDA, ...)` function. For example when the number of classes/labels equals the number of samples, the  resulting between-class covariance matrix is null, since in computing `Hw` there is only one member per class group which is then subtracted from itself when centering the data.
cc. @ablaom @wildart
> Detection of degenerate between-class covariance matrix

- docs/src/lda.md
- src/lda.jl
The documentation of `fit` function for MulticlassLDA wasn't displayed.
I think i fixed it. There is no example for LDA so i made a simple one but I am not sure you want it.
I can add it to the PR it you are interested. This is the scikit-learn example though.
```julia
using MultivariateStats, RDatasets, Plots
iris = dataset("datasets", "iris")
X = Matrix(iris[1:2:end,1:4])'
X_labels = Vector(iris[1:2:end,5])
pca = fit(PCA, X; maxoutdim=2)
Ypca = predict(pca, X)
lda = fit(MulticlassLDA, X, X_labels; outdim=2)
Ylda = predict(lda, X)
p = plot(layout=(1,2), size=(900,300))
for s in ["setosa", "versicolor", "virginica"]
points = Ypca[:,X_labels.==s]
scatter!(p[1], points[1,:],points[2,:],marker=:circle,linewidth=0, 
label=s, legend=:bottomleft)
points = Ylda[:,X_labels.==s]
scatter!(p[2], …
```
> MulticlassLDA documentation

- docs/source/kpca.rst
- src/kpca.jl
Bug: `fit(KernelPCA, X; kernel=nothing)` mutates `X` via `K = X` prior to calling `transform!` on `K`
Fix: `K = copy(X)`
Documentation also does not mention the use of `kernel=nothing` when `X` is a pre-computed Gramian; added this.
> Bug fix & documentation: KernelPCA w/ precomputed X

- Project.toml
- test/pca.jl
This is in preparation for https://github.com/JuliaLang/julia/pull/46196. Collecting index by index is relatively expensive compared to computing the entire matrix at once. Even though this is just a change in a test, I suggest to bump the patch version and to release it, so that nanosoldier tests can pick up the change.
> Matrixify `qr.Q` instead `collect`ing

- test/kpca.jl
otherwise, we require absolute equality when one of the values are 0.0
Due to the following difference in 1.11, this test otherwise fails:
```julia
julia> K = reshape(1.:12., 3, 4)
3×4 reshape(::StepRangeLen{Float64, Base.TwicePrecision{Float64}, Base.TwicePrecision{Float64}, Int64}, 3, 4) with eltype Float64:
1.0  4.0  7.0  10.0
2.0  5.0  8.0  11.0
3.0  6.0  9.0  12.0
julia> x, y = size(K)
(3, 4)
julia> I1 = ones(x,x)/x
3×3 Matrix{Float64}:
0.333333  0.333333  0.333333
0.333333  0.333333  0.333333
0.333333  0.333333  0.333333
julia> (- I1*K)[1,4]
-10.999999999999998
julia> (- I1*K)[1,4]
-11.0
```
> allow a bit of absolute tolerance deviation in a test,

- src/cmds.jl
- test/cmds.jl
When the embedding has a number of zero eigenvalues, `λ` gets truncated.
However, `U` does not, and thus `loadings` throws a `DimensionMismatch`
error on master. This fixes that error.
Alternatively, we could truncate `U` as well, but retaining the full `U`
matrix makes it easier to obtain a full orthonormal basis, if desired.
> Fix DimensionMismatch in `loadings`

- Project.toml
- src/MultivariateStats.jl
- src/cca.jl
- test/cca.jl
These are some of the classical hypothesis tests for CCA.  The results are identical against Stata.
> ENH: Add hypothesis tests for CCA

- Project.toml
#214 was missing [compat] for Distributions (see
https://github.com/JuliaRegistries/General/pull/108324), and we might
as well add for test dependencies and stdlibs while we're at it.
> Add missing [compat] entries
