.travis.yml
src/common.jl
src/lda.jl
src/lreg.jl
src/whiten.jl

which is handled in #11. Also enable testing on 0.3 and 0.4 and move the coverage submission to a `after_auccess` block.

Substitute FloatingPoint -> AbstractFloat in all files except pca.jl

---

README.md

Will tag a new version after this

Add 0.5 badge, remove 0.3 badge

---

README.md
docs/source/index.rst
docs/source/pca.rst
docs/source/ppca.rst
src/MultivariateStats.jl
src/ppca.jl
test/ppca.jl
test/runtests.jl

Added basic Probabilistic PCA implementation with following methods:
- Maximum Likelihood
- EM
- Bayesian

Implementation of Probabilistic PCA

---

.travis.yml
REQUIRE
src/MultivariateStats.jl
src/cmds.jl
src/ica.jl
src/lda.jl
src/pca.jl
src/ppca.jl
src/whiten.jl
test/cca.jl
test/cmds.jl
test/ica.jl
test/lda.jl
test/lreg.jl
test/mclda.jl
test/pca.jl
test/ppca.jl
test/runtests.jl
test/whiten.jl

Updates for Julia 0.6

---

README.md
docs/source/fa.rst
docs/source/index.rst
docs/source/ppca.rst
src/MultivariateStats.jl
src/fa.jl
test/fa.jl
test/runtests.jl

Added Factor Analysis implementation with following methods:
- EM
- CM (conditional maximization)

Implementation of Factor Analysis

---

README.md
docs/source/index.rst
docs/source/kpca.rst
src/MultivariateStats.jl
src/kpca.jl
test/kpca.jl
test/runtests.jl

Ref  #41
Basic implementation of Kernel PCA which works with various matrix types (dense and sparse) and data types.

Implementation of Kernel PCA

---

.travis.yml
README.md
REQUIRE

Once this is merged, FemtoCleaner will take care of the rest.

Drop support for Julia 0.5

---

src/ica.jl
test/ica.jl

This PR allows to call ICA with any data type.
N.B. Partially related to #19.

Make ICA call invariant to data type

---

src/lda.jl
test/lda.jl

This PR fixes LDA input data type constraints and some 0.7 deprecation warnings.

Fixed LDA input data type constraints

---

docs/source/pca.rst

I could've done with a more fleshed-out PCA example, so here's a suggestion

Added an extended PCA example with the iris dataset and plotting

---

src/ica.jl
test/ica.jl

ICA Fixes:
- Fixed convergence criteria (closes #45)
- Relaxed data input parameter type
- Added testsets
- Removed `Printf` dependency

Various ICA fixes

---

docs/source/lreg.rst
docs/source/mclda.rst
src/fa.jl
src/kpca.jl
src/lreg.jl
src/pca.jl
src/ppca.jl
src/whiten.jl

- updated parameter types
- user `Real' everywhere
- switch to `@debug` all logging messages

Minor type & logging fixes

---

src/cmds.jl

cmds: change warn to at-warn for Julia 1.0+ compatibility

---

src/lda.jl
test/mclda.jl

Fix subspace LDA input type errors

---

src/kpca.jl
test/kpca.jl

KPCA: Optimize an embedding calculation

---

README.md

That package has been deprecated for years.

Remove mention of DimensionalityReduction.jl

---

docs/source/lda.rst

fixed depreciated code in the documentation

updated lda.rst

---

src/common.jl

fix #112: remove type constraint

---

.gitignore
src/cca.jl
src/cmds.jl
src/common.jl
src/fa.jl
src/ica.jl
src/kpca.jl
src/lda.jl
src/pca.jl
src/ppca.jl
src/whiten.jl
test/cca.jl
test/cmds.jl
test/fa.jl
test/ica.jl
test/kpca.jl
test/pca.jl
test/ppca.jl
test/runtests.jl
test/whiten.jl

Lift some of the type restrictions discussed in #139.

Lift type restrictions

---

docs/Project.toml
docs/make.jl
docs/src/index.md

Added build script and index page for Documenter-based docs

Documenter-based docs

---

docs/make.jl
docs/src/api.md
docs/src/index.md
docs/src/lda.md
src/MultivariateStats.jl
src/lda.jl
test/lda.jl

Derive LDA types from`StatsBase.RegressionModel`
Step towards Unified API (#109)

add `RegressionModel` interface to LDA methods

---

.github/workflows/ci.yml
docs/Project.toml
docs/make.jl
docs/src/api.md
docs/src/index.md
docs/src/mds.md
src/MultivariateStats.jl
src/cmds.jl
test/cmds.jl

Added new docs and functions to satisfy new API (#109).

Refactor MDS code and docs (for #109)

---

docs/src/api.md
docs/src/pca.md
src/MultivariateStats.jl
src/kpca.jl
src/pca.jl
test/kpca.jl

Refactor KPCA code and docs (for #109)

Refactor KPCA

---

docs/make.jl
docs/src/api.md
docs/src/ica.md
docs/src/index.md
src/MultivariateStats.jl
src/ica.jl
test/ica.jl

Refactor ICA code and docs (for #109)

Refactor ICA

---

docs/make.jl
docs/src/api.md
docs/src/cca.md
docs/src/index.md
src/MultivariateStats.jl
src/cca.jl
test/cca.jl

Refactor CCA code and docs (for #109)

Refactor CCA

---

docs/src/pca.md
src/MultivariateStats.jl
src/ppca.jl
test/ppca.jl

Refactor PPCA code and docs (for #109)

Refactor PPCA

---

docs/make.jl
docs/src/fa.md
docs/src/index.md
src/fa.jl
test/fa.jl

Refactor FA code and docs (for #109)

Refactor FA

---

Project.toml
src/MultivariateStats.jl
src/cmds.jl
src/common.jl
src/pca.jl
src/types.jl
test/cmds.jl
test/kpca.jl
test/pca.jl

Changes which dependencies are used to import from.

use API imports from StatsAPI & `pairwise` from StatsBase

---

src/lda.jl
test/mclda.jl

Expend input type for MC-LDA

---

test/fa.jl
test/ppca.jl

I missed these in my previous PR. This time I made sure it passes on https://github.com/JuliaLang/julia/pull/46196/.

Fix missed `AbstractQ` tests

---

src/lda.jl

Indent code blocks and unindent text blocks so that Documenter.jl picks it up right.

Fix lda.jl docstrings

---

src/fa.jl

Fixed a mismatch in the type declaration of the docstring and code in size and mean methods.

Fix docstring of fa.jl
